/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudentsImport } from './routes/students'
import { Route as EmployeesImport } from './routes/employees'
import { Route as IndexImport } from './routes/index'
import { Route as StudentsIndexImport } from './routes/students/index'
import { Route as EmployeesIndexImport } from './routes/employees/index'
import { Route as StudentsNewImport } from './routes/students/new'
import { Route as StudentsStudentIdImport } from './routes/students/$studentId'
import { Route as EmployeesNewImport } from './routes/employees/new'
import { Route as EmployeesEmployeeIdImport } from './routes/employees/$employeeId'
import { Route as EmployeesEmployeeIdIndexImport } from './routes/employees/$employeeId/index'
import { Route as EmployeesEmployeeIdPaymentsImport } from './routes/employees/$employeeId/payments'
import { Route as EmployeesEmployeeIdPaymentsIndexImport } from './routes/employees/$employeeId/payments.index'
import { Route as EmployeesEmployeeIdPaymentsNewImport } from './routes/employees/$employeeId/payments.new'
import { Route as EmployeesEmployeeIdPaymentsPaymentIdImport } from './routes/employees/$employeeId/payments.$paymentId'

// Create/Update Routes

const StudentsRoute = StudentsImport.update({
  path: '/students',
  getParentRoute: () => rootRoute,
} as any)

const EmployeesRoute = EmployeesImport.update({
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsIndexRoute = StudentsIndexImport.update({
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)

const EmployeesIndexRoute = EmployeesIndexImport.update({
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)

const StudentsNewRoute = StudentsNewImport.update({
  path: '/new',
  getParentRoute: () => StudentsRoute,
} as any)

const StudentsStudentIdRoute = StudentsStudentIdImport.update({
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)

const EmployeesNewRoute = EmployeesNewImport.update({
  path: '/new',
  getParentRoute: () => EmployeesRoute,
} as any)

const EmployeesEmployeeIdRoute = EmployeesEmployeeIdImport.update({
  path: '/$employeeId',
  getParentRoute: () => EmployeesRoute,
} as any)

const EmployeesEmployeeIdIndexRoute = EmployeesEmployeeIdIndexImport.update({
  path: '/',
  getParentRoute: () => EmployeesEmployeeIdRoute,
} as any)

const EmployeesEmployeeIdPaymentsRoute =
  EmployeesEmployeeIdPaymentsImport.update({
    path: '/payments',
    getParentRoute: () => EmployeesEmployeeIdRoute,
  } as any)

const EmployeesEmployeeIdPaymentsIndexRoute =
  EmployeesEmployeeIdPaymentsIndexImport.update({
    path: '/',
    getParentRoute: () => EmployeesEmployeeIdPaymentsRoute,
  } as any)

const EmployeesEmployeeIdPaymentsNewRoute =
  EmployeesEmployeeIdPaymentsNewImport.update({
    path: '/new',
    getParentRoute: () => EmployeesEmployeeIdPaymentsRoute,
  } as any)

const EmployeesEmployeeIdPaymentsPaymentIdRoute =
  EmployeesEmployeeIdPaymentsPaymentIdImport.update({
    path: '/$paymentId',
    getParentRoute: () => EmployeesEmployeeIdPaymentsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      preLoaderRoute: typeof EmployeesImport
      parentRoute: typeof rootRoute
    }
    '/students': {
      preLoaderRoute: typeof StudentsImport
      parentRoute: typeof rootRoute
    }
    '/employees/$employeeId': {
      preLoaderRoute: typeof EmployeesEmployeeIdImport
      parentRoute: typeof EmployeesImport
    }
    '/employees/new': {
      preLoaderRoute: typeof EmployeesNewImport
      parentRoute: typeof EmployeesImport
    }
    '/students/$studentId': {
      preLoaderRoute: typeof StudentsStudentIdImport
      parentRoute: typeof StudentsImport
    }
    '/students/new': {
      preLoaderRoute: typeof StudentsNewImport
      parentRoute: typeof StudentsImport
    }
    '/employees/': {
      preLoaderRoute: typeof EmployeesIndexImport
      parentRoute: typeof EmployeesImport
    }
    '/students/': {
      preLoaderRoute: typeof StudentsIndexImport
      parentRoute: typeof StudentsImport
    }
    '/employees/$employeeId/payments': {
      preLoaderRoute: typeof EmployeesEmployeeIdPaymentsImport
      parentRoute: typeof EmployeesEmployeeIdImport
    }
    '/employees/$employeeId/': {
      preLoaderRoute: typeof EmployeesEmployeeIdIndexImport
      parentRoute: typeof EmployeesEmployeeIdImport
    }
    '/employees/$employeeId/payments/$paymentId': {
      preLoaderRoute: typeof EmployeesEmployeeIdPaymentsPaymentIdImport
      parentRoute: typeof EmployeesEmployeeIdPaymentsImport
    }
    '/employees/$employeeId/payments/new': {
      preLoaderRoute: typeof EmployeesEmployeeIdPaymentsNewImport
      parentRoute: typeof EmployeesEmployeeIdPaymentsImport
    }
    '/employees/$employeeId/payments/': {
      preLoaderRoute: typeof EmployeesEmployeeIdPaymentsIndexImport
      parentRoute: typeof EmployeesEmployeeIdPaymentsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  EmployeesRoute.addChildren([
    EmployeesEmployeeIdRoute.addChildren([
      EmployeesEmployeeIdPaymentsRoute.addChildren([
        EmployeesEmployeeIdPaymentsPaymentIdRoute,
        EmployeesEmployeeIdPaymentsNewRoute,
        EmployeesEmployeeIdPaymentsIndexRoute,
      ]),
      EmployeesEmployeeIdIndexRoute,
    ]),
    EmployeesNewRoute,
    EmployeesIndexRoute,
  ]),
  StudentsRoute.addChildren([
    StudentsStudentIdRoute,
    StudentsNewRoute,
    StudentsIndexRoute,
  ]),
])

/* prettier-ignore-end */
