/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeesImport } from './routes/employees'
import { Route as EmployeesIndexImport } from './routes/employees.index'
import { Route as EmployeesNewImport } from './routes/employees.new'
import { Route as EmployeesEmployeeIdImport } from './routes/employees.$employeeId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const EmployeesRoute = EmployeesImport.update({
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EmployeesIndexRoute = EmployeesIndexImport.update({
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)

const EmployeesNewRoute = EmployeesNewImport.update({
  path: '/new',
  getParentRoute: () => EmployeesRoute,
} as any)

const EmployeesEmployeeIdRoute = EmployeesEmployeeIdImport.update({
  path: '/$employeeId',
  getParentRoute: () => EmployeesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      preLoaderRoute: typeof EmployeesImport
      parentRoute: typeof rootRoute
    }
    '/employees/$employeeId': {
      preLoaderRoute: typeof EmployeesEmployeeIdImport
      parentRoute: typeof EmployeesImport
    }
    '/employees/new': {
      preLoaderRoute: typeof EmployeesNewImport
      parentRoute: typeof EmployeesImport
    }
    '/employees/': {
      preLoaderRoute: typeof EmployeesIndexImport
      parentRoute: typeof EmployeesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  EmployeesRoute.addChildren([
    EmployeesEmployeeIdRoute,
    EmployeesNewRoute,
    EmployeesIndexRoute,
  ]),
])

/* prettier-ignore-end */
